[build]
  command = "npm install && npx prisma generate && npx esbuild src/index.ts --bundle --platform=node --format=esm --packages=external --outfile=dist/index.js && mkdir -p dummy-publish"
  functions = "netlify/functions"
  publish = "dummy-publish"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "bcryptjs"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true
